import { db } from '@/db';
import { forumPosts } from '@/db/schema';

async function main() {
    const samplePosts = [
        {
            userId: 'user_seed_01',
            title: 'How to Value a SaaS Business: Revenue Multiple vs. EBITDA',
            content: 'I\'ve been analyzing several SaaS acquisition opportunities and I\'m struggling with valuation methodologies. Most sellers are quoting 3-5x revenue multiples, but when I calculate EBITDA multiples, the numbers don\'t align.\n\nFor context, I\'m looking at businesses with $500K-$2M ARR, 70-80% gross margins, and growing 20-30% YoY. The sellers justify high revenue multiples by pointing to growth rates and customer retention metrics.\n\nWhat\'s the industry standard? Should I be focusing more on revenue multiples for high-growth SaaS, or should EBITDA always be the primary metric? I\'d love to hear from experienced buyers who\'ve closed deals in this range.\n\nAlso, how do you adjust multiples based on factors like customer concentration, churn rate, and technical debt?',
            categoryId: 1,
            likesCount: 0,
            commentsCount: 0,
            createdAt: new Date('2024-12-15T10:30:00Z').toISOString(),
            updatedAt: new Date('2024-12-15T10:30:00Z').toISOString(),
        },
        {
            userId: 'user_seed_02',
            title: 'Red Flags I Found During Due Diligence on a $1.5M Content Site',
            content: 'Just walked away from a content site deal and wanted to share the red flags that saved me from a bad acquisition. The site was listed at $1.5M (36x monthly profit) and looked solid on paper - consistent traffic, diversified monetization, clean financials.\n\nHowever, during deep due diligence, I discovered: 1) 40% of traffic came from a single article that was ranking for outdated information, 2) The seller had been using a PBN for backlinks which could trigger a Google penalty, 3) Three major ad partners were scheduled to change their terms unfavorably, 4) The content was heavily AI-generated without proper editing or fact-checking.\n\nThe seller was cooperative but clearly hadn\'t disclosed these issues upfront. When I raised concerns, they offered to reduce the price by 20%, but I decided the risk wasn\'t worth it even at a discount.\n\nLesson learned: Always verify traffic sources independently, use tools like Ahrefs to audit backlink profiles, and actually read through the content yourself. What other due diligence checks do you prioritize for content businesses?',
            categoryId: 2,
            likesCount: 0,
            commentsCount: 0,
            createdAt: new Date('2024-12-18T14:20:00Z').toISOString(),
            updatedAt: new Date('2024-12-18T14:20:00Z').toISOString(),
        },
        {
            userId: 'user_seed_03',
            title: 'Maximizing Content Site Revenue: Beyond Ads and Affiliates',
            content: 'I\'ve owned a niche content site for 18 months and have grown it from $3K/month to $12K/month in revenue. Currently monetizing through display ads (Mediavine) and affiliate commissions, but I\'m looking to diversify revenue streams further.\n\nI\'m considering: 1) Creating a premium membership area with exclusive content, 2) Selling digital products or courses related to my niche, 3) Offering consulting services to readers, 4) Building an email list for sponsored newsletter placements.\n\nMy traffic is about 200K monthly visitors, highly engaged audience in the personal finance niche. Email list has 15K subscribers with 35% open rates. The content is evergreen and requires minimal maintenance.\n\nHas anyone successfully added these revenue streams to a content business? What were the challenges and time investments? I\'m trying to increase valuation before potentially selling in 12-18 months, so want to ensure any new revenue streams are sustainable and attractive to buyers.',
            categoryId: 3,
            likesCount: 0,
            commentsCount: 0,
            createdAt: new Date('2024-12-10T09:15:00Z').toISOString(),
            updatedAt: new Date('2024-12-10T09:15:00Z').toISOString(),
        },
        {
            userId: 'user_seed_04',
            title: 'First-Time Buyer: Should I Use SBA Loan or Personal Funds?',
            content: 'I\'ve found a great e-commerce business opportunity listed at $750K. The business has been around for 8 years, does about $2M in annual revenue with 25% profit margins, and is in a growing niche (sustainable home products).\n\nI have $300K in liquid assets and excellent credit (780+). My bank has pre-approved me for an SBA 7(a) loan up to $1M at 8.5% interest. However, I\'m debating whether to use the full loan amount or use more of my personal funds to reduce debt.\n\nOption A: Put down $150K (20%) and finance $600K - keeps more cash reserves but higher monthly payments. Option B: Put down $400K+ and finance $350K - lower payments but depletes my safety net.\n\nThe business cash flows well and could cover loan payments with room to spare, but I\'m nervous about being over-leveraged as a first-time buyer. The seller is offering seller financing for $100K over 3 years which would help bridge the gap.\n\nWhat would experienced buyers recommend? How much leverage is too much for your first acquisition?',
            categoryId: 1,
            likesCount: 0,
            commentsCount: 0,
            createdAt: new Date('2024-12-22T16:45:00Z').toISOString(),
            updatedAt: new Date('2024-12-22T16:45:00Z').toISOString(),
        },
        {
            userId: 'user_seed_05',
            title: 'E-commerce Business Due Diligence Checklist',
            content: 'After acquiring three e-commerce businesses over the past two years, I\'ve refined my due diligence process. Sharing my comprehensive checklist here for other buyers:\n\nFinancial Verification: 1) Request 3 years of P&L statements, 2) Verify revenue through platform dashboards (Shopify, Amazon, etc.), 3) Reconcile bank statements with reported revenue, 4) Analyze COGS and supplier agreements, 5) Review tax returns.\n\nOperational Review: 1) Inventory audit and valuation, 2) Supplier relationships and backup suppliers, 3) Fulfillment process and shipping costs, 4) Return rates and customer service metrics, 5) Software and subscription costs.\n\nMarketing & Traffic: 1) Verify traffic sources through Google Analytics, 2) Review paid advertising accounts and ROAS, 3) Email list verification and engagement metrics, 4) Social media following authenticity check, 5) SEO analysis and organic ranking stability.\n\nLegal & Compliance: 1) Trademark registration status, 2) Product compliance certifications, 3) Review customer complaints and legal issues, 4) Supplier contracts and exclusive agreements.\n\nWhat am I missing? Would love to hear what others prioritize.',
            categoryId: 2,
            likesCount: 0,
            commentsCount: 0,
            createdAt: new Date('2024-12-08T11:00:00Z').toISOString(),
            updatedAt: new Date('2024-12-08T11:00:00Z').toISOString(),
        },
        {
            userId: 'user_seed_06',
            title: 'Successfully Negotiated LOI - Lessons Learned',
            content: 'Just had my first LOI accepted on a $900K e-commerce business and wanted to share what worked in negotiations. The seller initially wanted $1.1M (4x EBITDA) but we settled at $900K with favorable terms.\n\nKey negotiation points: 1) I provided a detailed valuation analysis showing comparable sales in the niche, 2) Offered a faster close timeline (45 days vs. 90 days) in exchange for price reduction, 3) Agreed to keep the seller on as a consultant for 6 months at $5K/month, 4) Structured deal as $650K cash + $250K seller note over 24 months.\n\nWhat really helped: 1) Being pre-qualified with lender and showing proof of funds immediately, 2) Building rapport with seller through multiple video calls, 3) Highlighting my relevant experience in the industry, 4) Being flexible on non-financial terms like transition timeline.\n\nMistakes to avoid: Don\'t make lowball offers that insult the seller. Don\'t focus only on price - terms matter just as much. Do your homework before negotiating so you can justify your offer with data.\n\nNow entering the due diligence phase - wish me luck!',
            categoryId: 1,
            likesCount: 0,
            commentsCount: 0,
            createdAt: new Date('2024-12-20T13:30:00Z').toISOString(),
            updatedAt: new Date('2024-12-20T13:30:00Z').toISOString(),
        },
        {
            userId: 'user_seed_07',
            title: 'Escrow Process Explained: What to Expect During Your First Deal',
            content: 'Going through my first business acquisition and the escrow process seemed intimidating at first. Now that I\'m halfway through, I wanted to demystify it for other first-time buyers.\n\nEscrow Timeline: Day 1-3: Escrow agreement signed by all parties. Buyer deposits funds (usually 10% of purchase price). Day 4-30: Due diligence period - buyer reviews all business documents, financials, and operations. Day 31-45: Final negotiations and purchase agreement finalization. Day 46-60: Remaining funds deposited, asset transfer begins, training period starts. Day 61+: Final verification, escrow releases funds to seller.\n\nCost Breakdown: Escrow fees typically 1-2% of purchase price, split between buyer and seller. Wire transfer fees ($25-50 per transaction). Legal fees for purchase agreement review ($2,000-5,000). Accounting fees for financial verification ($1,000-3,000).\n\nCommon Issues: Sellers not having all documentation organized. Delays in transferring domain names and social media accounts. Disputes over asset valuation (especially inventory). Payment processor holds on transferred accounts.\n\nChoosing an escrow service: I used Escrow.com - they have experience with online business acquisitions and integrate well with marketplaces. Fees were reasonable and customer service was responsive.\n\nPro tip: Have a detailed asset transfer checklist prepared before entering escrow. This prevents last-minute scrambling and delays.',
            categoryId: 4,
            likesCount: 0,
            commentsCount: 0,
            createdAt: new Date('2024-12-12T15:20:00Z').toISOString(),
            updatedAt: new Date('2024-12-12T15:20:00Z').toISOString(),
        },
        {
            userId: 'user_seed_08',
            title: 'Post-Acquisition Integration: 90-Day Plan That Actually Works',
            content: 'Recently closed on my second acquisition (SaaS business, $1.2M purchase price) and wanted to share the integration playbook that\'s working well. Many buyers focus all energy on finding and closing deals but underestimate the post-acquisition work.\n\nWeek 1-2 (Stabilization): Ensure all critical systems are transferred and operational. Set up monitoring for key metrics (MRR, churn, support tickets). Send introduction email to customers explaining the acquisition. Have daily check-ins with key team members. Document all processes and SOPs.\n\nWeek 3-4 (Quick Wins): Implement small improvements that don\'t require major changes. Fix obvious UX issues or bugs. Optimize pricing page and onboarding flow. Set up proper analytics if missing. Establish communication rhythm with team.\n\nMonth 2 (Assessment): Conduct thorough analysis of customer feedback and support tickets. Identify top 3 feature requests. Review marketing channels and ROI. Audit tech stack and identify redundancies. Create 6-month product roadmap.\n\nMonth 3 (Growth Initiatives): Launch first major feature or improvement. Ramp up marketing in best-performing channels. Hire key roles if needed. Start planning larger strategic initiatives.\n\nBiggest mistake I made in my first acquisition: Trying to change too much too quickly. Customers and team need stability during transition. Better to move slowly and deliberately than make hasty changes you\'ll regret.',
            categoryId: 5,
            likesCount: 0,
            commentsCount: 0,
            createdAt: new Date('2024-12-05T10:45:00Z').toISOString(),
            updatedAt: new Date('2024-12-05T10:45:00Z').toISOString(),
        },
        {
            userId: 'user_seed_09',
            title: 'Market Analysis: Why SaaS Multiples Are Dropping in 2024',
            content: 'I\'ve been tracking SaaS acquisition multiples for the past 18 months and noticed a significant downward trend. In 2022-2023, we saw 5-8x revenue multiples for quality SaaS businesses. In 2024, that\'s dropped to 3-5x revenue.\n\nKey factors driving the decline: 1) Higher interest rates making debt financing more expensive and hurting buyer demand. 2) Increased competition from AI tools disrupting many SaaS niches. 3) Economic uncertainty causing buyers to be more conservative. 4) More SaaS founders wanting to exit, increasing supply. 5) Stricter due diligence as buyers got burned by inflated metrics.\n\nWhat this means for buyers: Better opportunities to acquire quality businesses at reasonable prices. More negotiating power, especially for businesses with any weaknesses. Sellers more willing to offer financing or earnouts.\n\nWhat this means for sellers: Need to have rock-solid metrics and documentation. Should consider waiting if not urgent to sell. Focus on improving defensibility and reducing churn before listing. Be realistic about valuation expectations.\n\nInteresting trend I\'m seeing: Micro-SaaS businesses ($50K-$200K revenue) are holding value better than larger ones. These are often solopreneur-operated with lean operations and loyal customer bases. The barriers to entry are lower but so is the competition at this tier.\n\nWhat are others seeing in their niches? Are multiples compressing everywhere or just in certain sectors?',
            categoryId: 6,
            likesCount: 0,
            commentsCount: 0,
            createdAt: new Date('2024-12-17T09:00:00Z').toISOString(),
            updatedAt: new Date('2024-12-17T09:00:00Z').toISOString(),
        },
        {
            userId: 'user_seed_10',
            title: 'Seller Financing: Structuring a Deal That Works for Both Parties',
            content: 'I\'ve completed three acquisitions with seller financing and it\'s been crucial to getting deals done. Banks are tightening lending and many sellers are open to financing if structured properly.\n\nTypical Structure: 20-30% down payment in cash. Remaining balance paid over 24-36 months. Interest rate: 6-8% (negotiate based on risk). Personal guarantee from buyer. Security interest in business assets.\n\nWhy sellers agree to this: Get a higher total purchase price than all-cash offers. Spread tax burden over multiple years. Maintain some involvement during transition. Earn interest income on the note. Buyer has strong incentive to succeed since they have ongoing payments.\n\nWhy buyers prefer this: Less cash needed upfront. Use business cash flow to pay the note. Seller remains motivated to help during transition. More deals become possible.\n\nKey terms to negotiate: Early payment discount (e.g., 5% if paid off in 12 months). Performance-based acceleration (if business hits certain metrics). Cure periods if payment is late. What happens if business fails.\n\nMy experience: First deal was 30% down, 70% seller note over 3 years at 7% interest. Business performed well and I paid it off in 18 months with the early payment discount. Second deal was 40% down, 60% note over 2 years at 6%. Third deal had an earnout component tied to revenue growth.\n\nRed flags: Sellers who want 50%+ seller financing (they may not believe in the business). Sellers who refuse to include any personal assets as collateral. Unrealistic expectations about business performance post-sale.',
            categoryId: 4,
            likesCount: 0,
            commentsCount: 0,
            createdAt: new Date('2024-12-14T14:15:00Z').toISOString(),
            updatedAt: new Date('2024-12-14T14:15:00Z').toISOString(),
        },
        {
            userId: 'user_seed_01',
            title: 'Technical Due Diligence Checklist for SaaS Acquisitions',
            content: 'As a technical founder who\'s acquired multiple SaaS businesses, I\'ve learned that technical due diligence is just as important as financial DD. Here\'s my comprehensive checklist:\n\nCode & Infrastructure: Review codebase quality and documentation. Check for technical debt and deprecated dependencies. Verify backup systems and disaster recovery plans. Analyze hosting costs and scalability. Review security practices and past breaches.\n\nData & Privacy: Ensure GDPR/CCPA compliance. Verify data backup and retention policies. Check for proper encryption of sensitive data. Review third-party data processor agreements. Analyze data migration complexity.\n\nProduct & Architecture: Evaluate product roadmap and feasibility. Check API integrations and dependencies. Review mobile app quality if applicable. Assess ease of adding new features. Identify single points of failure.\n\nMetrics & Monitoring: Verify uptime and performance metrics. Check error tracking implementation. Review user analytics setup. Analyze load testing results. Evaluate alerting systems.\n\nRed flags I\'ve encountered: Code written by a single developer with no documentation. Using deprecated frameworks that require complete rewrite. No version control or sloppy Git history. Customer data stored insecurely. No automated testing whatsoever.\n\nPro tip: Hire a technical consultant if you\'re not technical yourself. The $2K-5K cost is worth it to avoid buying a technical nightmare.',
            categoryId: 2,
            likesCount: 0,
            commentsCount: 0,
            createdAt: new Date('2024-12-19T11:30:00Z').toISOString(),
            updatedAt: new Date('2024-12-19T11:30:00Z').toISOString(),
        },
        {
            userId: 'user_seed_02',
            title: 'Growing a Content Site After Acquisition: 6-Month Results',
            content: 'Acquired a content site 6 months ago for $180K (30x monthly profit) and wanted to share growth results and strategies. The site was making $6K/month when I bought it, now doing $11K/month.\n\nWhat I did: Published 40 new high-quality articles (outsourced to proven writers). Updated 30 older articles with fresh information. Built 20 high-quality backlinks through outreach. Migrated from AdSense to Mediavine (50% revenue increase). Added affiliate links to 50+ articles where relevant. Improved site speed from 3.5s to 1.2s load time.\n\nResults: Organic traffic up 65% (from 80K to 132K monthly visitors). Revenue per session increased 30%. Bounce rate decreased from 68% to 51%. 15 new keywords ranking in top 3 positions.\n\nInvestment: Content creation: $8,000. Backlink building: $2,500. Site speed optimization: $1,500. Tools and software: $500. Total: $12,500.\n\nROI: Additional $5K/month revenue ($30K over 6 months). ROI: 140% in 6 months. On track to break even on acquisition in 18 months total.\n\nLessons learned: Quality over quantity for content - better to publish 10 great articles than 50 mediocre ones. Site speed matters more than I expected. Don\'t neglect updating old content - it\'s often higher ROI than new content. Relationships with other site owners are valuable for backlinks.\n\nNext steps: Launch email newsletter (targeting 1,000 subscribers in 3 months). Create first digital product. Test video content for key articles.',
            categoryId: 3,
            likesCount: 0,
            commentsCount: 0,
            createdAt: new Date('2024-12-11T15:45:00Z').toISOString(),
            updatedAt: new Date('2024-12-11T15:45:00Z').toISOString(),
        },
        {
            userId: 'user_seed_03',
            title: 'Asset Transfer Guide: Avoiding Common Pitfalls',
            content: 'Just completed my third business acquisition and the asset transfer process has gotten smoother each time. Sharing a detailed guide to help others avoid the headaches I experienced in my first deal.\n\nDigital Assets: Domain transfer (allow 7-10 days, initiate early). Website hosting and files (download complete backup before transfer). Email accounts and history (export before canceling old accounts). Social media accounts (use proper transfer procedures, not password sharing). Cloud storage and files (Dropbox, Google Drive, etc.).\n\nBusiness Accounts: Payment processors (Stripe, PayPal - expect 2-4 week verification). Email marketing (export lists before transferring). CRM and customer data (ensure clean export). Analytics accounts (Google Analytics, proper access transfer). Advertising accounts (Facebook, Google Ads - verify business manager transfer).\n\nIntellectual Property: Trademark assignments (file with USPTO, 3-6 months processing). Copyright transfer documentation. Domain ownership (ensure proper registrant change). Brand assets and design files.\n\nSupplier & Partner Relationships: Introduce yourself to key suppliers early. Update billing information. Renegotiate terms if possible. Verify contracts are assignable.\n\nCommon mistakes: Waiting until closing day to start transfers (start during due diligence where possible). Not documenting every transferred asset. Assuming password sharing is sufficient for accounts. Forgetting about less obvious assets (analytics, webhooks, integrations).\n\nPro tip: Create a shared checklist with the seller in a tool like Notion or Airtable. Check off items as completed. This prevents missed items and reduces post-close cleanup.',
            categoryId: 5,
            likesCount: 0,
            commentsCount: 0,
            createdAt: new Date('2024-12-16T12:00:00Z').toISOString(),
            updatedAt: new Date('2024-12-16T12:00:00Z').toISOString(),
        },
        {
            userId: 'user_seed_04',
            title: 'E-commerce Trends for 2025: Where Smart Money is Going',
            content: 'After attending three acquisition conferences and speaking with dozens of buyers and brokers, I\'ve identified key e-commerce trends that will shape acquisitions in 2025.\n\nHot Niches: Sustainability and eco-friendly products (growing 40% YoY). Health and wellness (aging demographics driving growth). Pet products (recession-resistant, high margins). Home organization and productivity tools. Outdoor and adventure gear (post-pandemic trend holding strong).\n\nCooling Niches: Pandemic-specific products (work from home accessories declining). Fidget toys and similar fads. Generic dropshipping stores. Heavily Amazon-dependent businesses (3P seller risk too high).\n\nBuyer Preferences: Businesses with owned inventory (not dropshipping). Multiple sales channels (own website + Amazon + retail). Email lists over 20K engaged subscribers. Repeat customer rates above 25%. Strong social media presence and community.\n\nValuation Trends: Physical products: 2.5-3.5x EBITDA. Subscription boxes: 3-4x EBITDA. D2C brands with strong IP: 3.5-4.5x EBITDA. Amazon FBA only: 2-3x EBITDA (higher risk discount).\n\nEmerging Opportunities: Aggregators struggling and selling individual brands at discount. International expansion potential undervalued. Subscription model conversion potential. B2B e-commerce underpriced vs. B2C.\n\nMy prediction: 2025 will be a great year for buyers with cash or SBA financing. Sellers who can demonstrate defensibility and growth potential will still command premiums, but average multiples will remain 10-15% below 2021-2022 peaks.',
            categoryId: 6,
            likesCount: 0,
            commentsCount: 0,
            createdAt: new Date('2024-12-21T10:30:00Z').toISOString(),
            updatedAt: new Date('2024-12-21T10:30:00Z').toISOString(),
        },
        {
            userId: 'user_seed_05',
            title: 'How to Negotiate Better Deal Terms (Beyond Just Price)',
            content: 'After negotiating five acquisitions, I\'ve learned that deal terms often matter more than the headline price. Here are the key terms I always negotiate:\n\nTransition Support: Duration (30-90 days typical, negotiate for more if needed). Scope (documentation, training, customer introductions). Availability (daily calls vs. weekly, what hours). Compensation (usually included, but sometimes paid separately).\n\nWarranties and Representations: Financial accuracy (typically warranted for 12-24 months). Customer retention guarantees (refund if major customers leave). Intellectual property ownership. No undisclosed liabilities.\n\nPayment Structure: Upfront cash percentage. Seller financing terms (rate, duration, security). Earnout provisions (if any, tied to specific metrics). Escrow holdback amount and duration.\n\nNon-Compete and Non-Solicitation: Geographic scope (be reasonable but protective). Duration (2-5 years typical). Covered activities (similar businesses, customers, employees). Exceptions (if any).\n\nAsset Transfers: Timeline and responsibilities. Who pays transfer fees. What happens if transfers fail. Backup plans for critical assets.\n\nExample from my deals: Deal 1 - Negotiated 90 days of seller support (vs. 30 days offered) for same price. Deal 2 - Added 10% escrow holdback for 6 months to cover warranties. Deal 3 - Structured earnout where I only pay additional 20% if revenue grows 25%+ in year 1. Deal 4 - Extended non-compete from 2 years to 4 years in exchange for 5% price reduction. Deal 5 - Negotiated seller to retain certain liabilities (old marketing commitments).\n\nKey insight: Sellers often focus on headline price and will make concessions on terms to maintain that number. Use this to your advantage.',
            categoryId: 1,
            likesCount: 0,
            commentsCount: 0,
            createdAt: new Date('2024-12-13T16:20:00Z').toISOString(),
            updatedAt: new Date('2024-12-13T16:20:00Z').toISOString(),
        },
    ];

    await db.insert(forumPosts).values(samplePosts);
    
    console.log('✅ Forum posts seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});