import { db } from '@/db';
import { listings } from '@/db/schema';

async function main() {
    const sampleListings = [
        {
            sellerId: 'user_seed_01',
            title: 'Cloud-Based Project Management SaaS',
            businessType: 'SaaS',
            businessModel: 'Subscription',
            niche: 'Productivity',
            geography: 'Global',
            ttmRevenue: 480000,
            ttmProfit: 120000,
            profitMargin: 25,
            askingPrice: 1200000,
            revenueMultiple: 2.5,
            ageMonths: 36,
            teamSize: 3,
            hoursPerWeek: 20,
            fullDescription: 'Established project management platform with 2000+ active subscribers. Features include task management, team collaboration, time tracking, and reporting. Built on modern tech stack with scalable infrastructure. Strong customer retention rate of 92% and consistent MRR growth of 15% quarterly.',
            businessUrl: 'https://example-pm.com',
            brandName: 'TaskFlow Pro',
            organicTraffic: '25000',
            paidTraffic: '5000',
            status: 'approved',
            isVerified: true,
            underLoi: false,
            sellerResponseTimeHours: 24,
            approvedAt: new Date('2024-01-15'),
            submittedAt: new Date('2024-01-10'),
            createdAt: new Date('2024-01-05'),
            updatedAt: new Date('2024-01-15'),
        },
        {
            sellerId: 'user_seed_02',
            title: 'Premium Fashion eCommerce Store',
            businessType: 'eCom',
            businessModel: 'Direct to Consumer',
            niche: 'Fashion & Apparel',
            geography: 'United States',
            ttmRevenue: 850000,
            ttmProfit: 212500,
            profitMargin: 25,
            askingPrice: 2550000,
            revenueMultiple: 3.0,
            ageMonths: 48,
            teamSize: 5,
            hoursPerWeek: 30,
            fullDescription: 'High-end fashion eCommerce store specializing in sustainable and ethical clothing. Established brand with loyal customer base of 15,000+ repeat customers. Strong social media presence with 50k Instagram followers. Owns inventory and has exclusive supplier relationships. Average order value of $150.',
            businessUrl: 'https://example-fashion.com',
            brandName: 'EcoStyle Fashion',
            organicTraffic: '45000',
            paidTraffic: '15000',
            marketplaces: 'Shopify, Instagram Shop',
            status: 'approved',
            isVerified: true,
            underLoi: false,
            sellerResponseTimeHours: 12,
            approvedAt: new Date('2024-01-20'),
            submittedAt: new Date('2024-01-15'),
            createdAt: new Date('2024-01-10'),
            updatedAt: new Date('2024-01-20'),
        },
        {
            sellerId: 'user_seed_03',
            title: 'SEO Content Network - Finance Niche',
            businessType: 'Content',
            businessModel: 'Advertising',
            niche: 'Finance',
            geography: 'Global',
            ttmRevenue: 320000,
            ttmProfit: 256000,
            profitMargin: 80,
            askingPrice: 960000,
            revenueMultiple: 3.0,
            ageMonths: 60,
            teamSize: 2,
            hoursPerWeek: 10,
            fullDescription: 'Profitable content network of 5 finance-related websites generating consistent passive income through display ads and affiliate marketing. Combined monthly traffic of 500k visitors. All sites ranking on first page for multiple high-value keywords. Minimal maintenance required with outsourced content production.',
            businessUrl: 'https://example-finance-network.com',
            brandName: 'Finance Hub Network',
            organicTraffic: '500000',
            paidTraffic: '0',
            status: 'approved',
            isVerified: true,
            underLoi: false,
            sellerResponseTimeHours: 48,
            approvedAt: new Date('2024-01-25'),
            submittedAt: new Date('2024-01-22'),
            createdAt: new Date('2024-01-18'),
            updatedAt: new Date('2024-01-25'),
        },
        {
            sellerId: 'user_seed_04',
            title: 'Mobile Fitness Tracking App',
            businessType: 'Apps',
            businessModel: 'Freemium',
            niche: 'Health & Fitness',
            geography: 'Global',
            ttmRevenue: 180000,
            ttmProfit: 135000,
            profitMargin: 75,
            askingPrice: 540000,
            revenueMultiple: 3.0,
            ageMonths: 24,
            teamSize: 2,
            hoursPerWeek: 15,
            fullDescription: 'iOS and Android fitness tracking app with 100,000+ downloads and 5,000 paying subscribers. Features include workout tracking, nutrition logging, and progress analytics. 4.5-star rating on both app stores. Strong user engagement with daily active users at 15,000. Clean codebase and scalable backend infrastructure.',
            businessUrl: 'https://example-fitness-app.com',
            brandName: 'FitTrack Pro',
            organicTraffic: '8000',
            paidTraffic: '2000',
            marketplaces: 'App Store, Google Play',
            status: 'approved',
            isVerified: true,
            underLoi: false,
            sellerResponseTimeHours: 24,
            approvedAt: new Date('2024-02-01'),
            submittedAt: new Date('2024-01-28'),
            createdAt: new Date('2024-01-25'),
            updatedAt: new Date('2024-02-01'),
        },
        {
            sellerId: 'user_seed_05',
            title: 'B2B Lead Generation SaaS Platform',
            businessType: 'SaaS',
            businessModel: 'Subscription',
            niche: 'Marketing',
            geography: 'United States',
            ttmRevenue: 650000,
            ttmProfit: 325000,
            profitMargin: 50,
            askingPrice: 1950000,
            revenueMultiple: 3.0,
            ageMonths: 42,
            teamSize: 4,
            hoursPerWeek: 25,
            fullDescription: 'B2B lead generation platform serving 500+ business clients. Provides verified contact data, email verification, and CRM integration. High customer lifetime value with average subscription duration of 18 months. Strong technical infrastructure with proprietary data scraping algorithms. Recurring revenue model with 95% retention rate.',
            businessUrl: 'https://example-leads.com',
            brandName: 'LeadForge',
            organicTraffic: '35000',
            paidTraffic: '10000',
            status: 'approved',
            isVerified: true,
            underLoi: false,
            sellerResponseTimeHours: 18,
            approvedAt: new Date('2024-02-05'),
            submittedAt: new Date('2024-02-01'),
            createdAt: new Date('2024-01-28'),
            updatedAt: new Date('2024-02-05'),
        },
        {
            sellerId: 'user_seed_06',
            title: 'Amazon FBA Home & Kitchen Brand',
            businessType: 'eCom',
            businessModel: 'FBA',
            niche: 'Home & Kitchen',
            geography: 'United States',
            ttmRevenue: 1200000,
            ttmProfit: 360000,
            profitMargin: 30,
            askingPrice: 3240000,
            revenueMultiple: 2.7,
            ageMonths: 36,
            teamSize: 3,
            hoursPerWeek: 20,
            fullDescription: 'Established Amazon FBA brand with 12 SKUs in home and kitchen category. Multiple bestseller rankings and 1000+ verified reviews with 4.7-star average. Strong trademark and IP protection. Diversified supplier relationships. Inventory included in sale. Consistent sales velocity with low return rates.',
            businessUrl: 'https://amazon.com/stores/example',
            brandName: 'HomeEssentials Pro',
            organicTraffic: '0',
            paidTraffic: '0',
            marketplaces: 'Amazon FBA',
            status: 'approved',
            isVerified: true,
            underLoi: true,
            sellerResponseTimeHours: 12,
            approvedAt: new Date('2024-02-08'),
            submittedAt: new Date('2024-02-05'),
            createdAt: new Date('2024-02-01'),
            updatedAt: new Date('2024-02-08'),
        },
        {
            sellerId: 'user_seed_07',
            title: 'Tech Review Affiliate Website',
            businessType: 'Content',
            businessModel: 'Affiliate',
            niche: 'Technology',
            geography: 'Global',
            ttmRevenue: 240000,
            ttmProfit: 216000,
            profitMargin: 90,
            askingPrice: 720000,
            revenueMultiple: 3.0,
            ageMonths: 54,
            teamSize: 1,
            hoursPerWeek: 8,
            fullDescription: 'Established tech review website monetized through Amazon Associates and direct affiliate partnerships. 300+ in-depth product reviews and buying guides. Monthly traffic of 180,000 visitors with strong SEO rankings for money keywords. Very hands-off operation with content writers on retainer. Email list of 25,000 subscribers.',
            businessUrl: 'https://example-tech-reviews.com',
            brandName: 'TechInsider Reviews',
            organicTraffic: '180000',
            paidTraffic: '0',
            status: 'approved',
            isVerified: true,
            underLoi: false,
            sellerResponseTimeHours: 36,
            approvedAt: new Date('2024-02-12'),
            submittedAt: new Date('2024-02-08'),
            createdAt: new Date('2024-02-05'),
            updatedAt: new Date('2024-02-12'),
        },
        {
            sellerId: 'user_seed_08',
            title: 'Online Education Platform - Programming Courses',
            businessType: 'SaaS',
            businessModel: 'Subscription',
            niche: 'Education',
            geography: 'Global',
            ttmRevenue: 890000,
            ttmProfit: 534000,
            profitMargin: 60,
            askingPrice: 2670000,
            revenueMultiple: 3.0,
            ageMonths: 48,
            teamSize: 6,
            hoursPerWeek: 30,
            fullDescription: 'Online learning platform offering programming and web development courses. 15,000 active students with course completion rate of 68%. Library of 50+ courses with video content, coding exercises, and certificates. Strong brand recognition in developer community. Mix of one-time purchases and monthly subscriptions generating stable recurring revenue.',
            businessUrl: 'https://example-codeacademy.com',
            brandName: 'CodeMaster Academy',
            organicTraffic: '65000',
            paidTraffic: '20000',
            status: 'approved',
            isVerified: true,
            underLoi: false,
            sellerResponseTimeHours: 24,
            approvedAt: new Date('2024-02-15'),
            submittedAt: new Date('2024-02-12'),
            createdAt: new Date('2024-02-08'),
            updatedAt: new Date('2024-02-15'),
        },
        {
            sellerId: 'user_seed_09',
            title: 'Dropshipping Store - Pet Supplies',
            businessType: 'eCom',
            businessModel: 'Dropshipping',
            niche: 'Pets',
            geography: 'United States',
            ttmRevenue: 420000,
            ttmProfit: 84000,
            profitMargin: 20,
            askingPrice: 336000,
            revenueMultiple: 4.0,
            ageMonths: 18,
            teamSize: 2,
            hoursPerWeek: 15,
            fullDescription: 'Profitable dropshipping store specializing in premium pet supplies and accessories. Automated order processing with reliable supplier network. Strong customer service record with 4.8-star rating. Active email list of 12,000 pet owners. Effective Facebook and Instagram advertising campaigns with positive ROAS. Shopify store with optimized conversion funnel.',
            businessUrl: 'https://example-pet-supplies.com',
            brandName: 'PawfectLife Supplies',
            organicTraffic: '15000',
            paidTraffic: '25000',
            marketplaces: 'Shopify',
            status: 'approved',
            isVerified: true,
            underLoi: false,
            sellerResponseTimeHours: 24,
            approvedAt: new Date('2024-02-18'),
            submittedAt: new Date('2024-02-15'),
            createdAt: new Date('2024-02-12'),
            updatedAt: new Date('2024-02-18'),
        },
        {
            sellerId: 'user_seed_10',
            title: 'WordPress SEO Plugin - Premium Version',
            businessType: 'SaaS',
            businessModel: 'Freemium',
            niche: 'Marketing',
            geography: 'Global',
            ttmRevenue: 280000,
            ttmProfit: 224000,
            profitMargin: 80,
            askingPrice: 840000,
            revenueMultiple: 3.0,
            ageMonths: 30,
            teamSize: 2,
            hoursPerWeek: 12,
            fullDescription: 'Popular WordPress SEO plugin with 50,000+ active installations and 4.9-star rating. Freemium model with 2,000 premium subscribers. Features include keyword optimization, schema markup, and content analysis. Regular updates and excellent support reputation. Low churn rate of 5% monthly. Listed on WordPress.org plugin directory with strong organic discovery.',
            businessUrl: 'https://example-seo-plugin.com',
            brandName: 'SEO Boost Pro',
            organicTraffic: '42000',
            paidTraffic: '3000',
            marketplaces: 'WordPress.org',
            status: 'approved',
            isVerified: true,
            underLoi: false,
            sellerResponseTimeHours: 24,
            approvedAt: new Date('2024-02-22'),
            submittedAt: new Date('2024-02-18'),
            createdAt: new Date('2024-02-15'),
            updatedAt: new Date('2024-02-22'),
        },
    ];

    await db.insert(listings).values(sampleListings);
    
    console.log('✅ Listings seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});