import { db } from '@/db';
import { marketplaceListings } from '@/db/schema';

async function main() {
    const sampleListings = [
        {
            title: 'Premium SaaS Platform',
            location: 'United States',
            category: 'SaaS',
            price: 45000000,
            annualRevenue: 28000000,
            annualCashFlow: 12000000,
            description: 'B2B SaaS with 500+ paying customers, 95% net revenue retention, stable MRR/ARR, and automated onboarding.',
            isFeatured: true,
            isVerified: true,
            employees: 8,
            yearEstablished: 2018,
            createdAt: new Date('2024-01-15').getTime(),
            updatedAt: new Date('2024-01-15').getTime(),
        },
        {
            title: 'SEO & Content Analytics Tool (SaaS)',
            location: 'United Kingdom',
            category: 'SaaS',
            price: 52000000,
            annualRevenue: 34000000,
            annualCashFlow: 15000000,
            description: 'SEO dashboard with GA4/Search Console integrations, 1,200+ subscribers, low churn, and strong organic growth.',
            isFeatured: true,
            isVerified: true,
            employees: 6,
            yearEstablished: 2019,
            createdAt: new Date('2024-01-18').getTime(),
            updatedAt: new Date('2024-01-18').getTime(),
        },
        {
            title: 'E‑commerce Brand (DTC)',
            location: 'Germany',
            category: 'E‑commerce',
            price: 32000000,
            annualRevenue: 45000000,
            annualCashFlow: 9500000,
            description: 'DTC store with diversified channels (Meta/Google/Email/SMS), 40% repeat rate, 3PL and automation — no warehouses.',
            isFeatured: false,
            isVerified: true,
            employees: 5,
            yearEstablished: 2019,
            createdAt: new Date('2024-01-20').getTime(),
            updatedAt: new Date('2024-01-20').getTime(),
        },
        {
            title: 'Digital Marketing Agency',
            location: 'Canada',
            category: 'Digital Agency',
            price: 58000000,
            annualRevenue: 72000000,
            annualCashFlow: 18500000,
            description: 'Retainer clients for SEO, PPC and CRO. Documented SOPs, HubSpot CRM, and automated processes.',
            isFeatured: true,
            isVerified: true,
            employees: 12,
            yearEstablished: 2008,
            createdAt: new Date('2024-01-22').getTime(),
            updatedAt: new Date('2024-01-22').getTime(),
        },
        {
            title: 'Subscription Newsletter Business',
            location: 'Australia',
            category: 'Media & Newsletters',
            price: 26000000,
            annualRevenue: 21000000,
            annualCashFlow: 11000000,
            description: '85k subscribers, revenue from sponsorships and paid tiers. High open rates, strong CPMs, and growth via partnerships.',
            isFeatured: false,
            isVerified: true,
            employees: 3,
            yearEstablished: 2020,
            createdAt: new Date('2024-01-25').getTime(),
            updatedAt: new Date('2024-01-25').getTime(),
        },
        {
            title: 'Mobile Productivity App',
            location: 'Singapore',
            category: 'Mobile Apps',
            price: 39000000,
            annualRevenue: 30000000,
            annualCashFlow: 14000000,
            description: 'iOS/Android app with subscriptions, strong ASO, and automated onboarding. Well-documented code and CI/CD.',
            isFeatured: false,
            isVerified: true,
            employees: 4,
            yearEstablished: 2017,
            createdAt: new Date('2024-01-28').getTime(),
            updatedAt: new Date('2024-01-28').getTime(),
        },
        {
            title: 'Dropshipping Store (Automation Ready)',
            location: 'France',
            category: 'Dropshipping',
            price: 22500000,
            annualRevenue: 38000000,
            annualCashFlow: 11500000,
            description: 'Shopify store with vetted suppliers, automated fulfillment, and profitable paid channels. No inventory and no warehouses.',
            isFeatured: false,
            isVerified: true,
            employees: 2,
            yearEstablished: 2021,
            createdAt: new Date('2024-02-01').getTime(),
            updatedAt: new Date('2024-02-01').getTime(),
        },
        {
            title: 'YouTube Channel + Digital Products',
            location: 'United Arab Emirates',
            category: 'Creator Business',
            price: 31000000,
            annualRevenue: 27000000,
            annualCashFlow: 13000000,
            description: '450k subscribers, diversified revenue (ads, sponsorships, courses). Strong SEO, evergreen content, and engaged community.',
            isFeatured: false,
            isVerified: true,
            employees: 2,
            yearEstablished: 2016,
            createdAt: new Date('2024-02-03').getTime(),
            updatedAt: new Date('2024-02-03').getTime(),
        },
        {
            title: 'Fintech Micro‑SaaS',
            location: 'Spain',
            category: 'Fintech',
            price: 56000000,
            annualRevenue: 36000000,
            annualCashFlow: 17000000,
            description: 'Niche financial automation with bank/Stripe integrations, low churn, and enterprise upsell. SOC2‑ready.',
            isFeatured: true,
            isVerified: true,
            employees: 7,
            yearEstablished: 2018,
            createdAt: new Date('2024-02-05').getTime(),
            updatedAt: new Date('2024-02-05').getTime(),
        },
    ];

    await db.insert(marketplaceListings).values(sampleListings);
    
    console.log('✅ Marketplace listings seeder completed successfully');
}

main().catch((error) => {
    console.error('❌ Seeder failed:', error);
});